[tools]
node = "latest"
bun = "latest"
python = "latest"
rust = "latest"
ruby = "latest"
java = "latest"
uv = "latest"
pi = "latest"
gcloud = "latest"
"npm:@googleworkspace/cli" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["bun"]
experimental = true

[settings.python]
uv_venv_auto = true

[env]
